#!/usr/bin/perl -w

my $file = "";
my $path = "";
my $name = "";

# no enough argument
die "Usage: rncomponent [path]\n" if (@ARGV == 0);
$file = './' . $ARGV[0];
# deal with extra .js
if ($file =~ /\.js$/) {
    $path = $file;
    # remove .js
    $file = s/\.js//g;
}
if ($file =~ /.*\/([\d\w\.\/]+)$/) {
    my $match = $1;
    $file =~ /$match/;
    $name = ucfirst $1;
}

# check if name is good (numbers, letters and . / only)
print "file: $file\npath: $path\n";
die "$file is not legit\n" if ($file =~ /[^\d\w\.\/]/);
die "\nrncomponent------\ncreates a template for your new components\nRead more: https://github.com/HenryQuan/rncomponent/\n\n" if (lc $file eq "--about");

# check if file already exists

die "$file.js already exists\n" if (-e "$file.js");

# write into the file
open  my $F, ">", $path . "$file.js" or die "I/O error";
print $F "import React, { Component } from 'react';" . "\n" .
    "import { View, Text, StyleSheet } from 'react-native';" . "\n\n" .
    "class $file extends Component {" . "\n" .
    "  render() {" . "\n" .
    "    const { container } = styles;" . "\n" .
    "    return (" . "\n" .
    "      <View style={container}>" . "\n" .
    "        <Text>$file</Text>" . "\n" .
    "      </View>" . "\n" .
    "    )" . "\n" .
    "  };" . "\n" .
    "}" . "\n\n" .
    "const styles = StyleSheet.create({" . "\n" .
    "  container: {" . "\n" .
    "    flex: 1," . "\n" .
    "    alignItems: 'center'," . "\n" .
    "    justifyContent: 'center'" . "\n" .
    "  }" . "\n" .
    "});" . "\n\n" .
    "export { $file };" . "\n" or die;
close $F;
print "$file.js has been created\n"
